GameLibrary/Models/SCart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameLibrary.Models
{
    public class SCart
    {
        public string SCartId { get; set; }
        public List<SCartItem> SCartItems { get; set; }

        private readonly StoreContext _context;

        private SCart(StoreContext context)
        {
            _context = context;
        }

        public static SCart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?
                .HttpContext.Session;

            var context = services.GetService<StoreContext>();
            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();

            session.SetString("CartId", cartId);

            return new SCart(context) { SCartId = cartId };
        }

        public void AddToCart(Book book, int amount)
        {
            var sCartItem = _context.SCartItems.SingleOrDefault(
                s => s.Book.BookID == book.BookID && s.SCartId == SCartId);

            if(sCartItem == null)
            {
                sCartItem = new SCartItem
                {
                    SCartId = SCartId,
                    Book = book,
                    Amount = 1
                };
                _context.SCartItems.Add(sCartItem);

            }
            else
            {
                sCartItem.Amount++;
            }

            _context.SaveChanges();
        }

        public int RemoveFromCart(Book book)
        {
            var sCartItem = _context.SCartItems.SingleOrDefault(
                s => s.Book.BookID == book.BookID && s.SCartId == SCartId);

            var localAmount = 0;

            if(sCartItem != null)
            {
                if(sCartItem.Amount > 1)
                {
                    sCartItem.Amount--;
                    localAmount = sCartItem.Amount;
                }
                else
                {
                    _context.SCartItems.Remove(sCartItem);
                }
            }

            _context.SaveChanges();

            return localAmount;
        }

        public List<SCartItem> GetShoppingCartItems()
        {
            return SCartItems ??
                (SCartItems = _context.SCartItems.Where(c => c.SCartId == SCartId)
                .Include(s => s.Book)
                .ToList());
        }

        public void ClearCart()
        {
            var cartItems = _context.SCartItems.Where(cart => cart.SCartId == SCartId);

            _context.SCartItems.RemoveRange(cartItems);

            _context.SaveChanges();
        }

        public float GetShoppingCartTotal()
        {
            var total = _context.SCartItems.Where(c => c.SCartId == SCartId)
                .Select(c => c.Book.BookPrice * c.Amount).Sum();

            return total;
        }
    }

    
}

GameLibrary/ViewModels/SCartViewModel.cs
using GameLibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameLibrary.ViewModels
{
    public class SCartViewModel
    {
        public SCart SCart { get; set; }
        public float SCartTotal { get; set; }
    }
}

GameLibrary/Controllers/SCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameLibrary.Models;
using GameLibrary.ViewModels;

namespace GameLibrary.Controllers
{
    public class SCartsController : Controller
    {
        private readonly StoreContext _context;
        private readonly IBookRepository _bookRepository;
        private readonly SCart _sCart;

        public SCartsController(StoreContext context, IBookRepository bookRepository, SCart sCart)
        {
            _context = context;
            _bookRepository = bookRepository;
            _sCart = sCart;
        }

        public ViewResult Index()
        {
            var items = _sCart.GetShoppingCartItems();
            _sCart.SCartItems = items;

            var sCVM = new SCartViewModel
            {
                SCart = _sCart,
                SCartTotal = _sCart.GetShoppingCartTotal()
            };

            return View(sCVM);
        }

        public RedirectToActionResult AddToShoppingCart(int bookId)
        {
            var selectedBook = _bookRepository.Books.FirstOrDefault(p => p.BookID == bookId);
            if (selectedBook != null)
            {
                _sCart.AddToCart(selectedBook, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int bookId)
        {
            var selectedBook = _bookRepository.Books.FirstOrDefault(p => p.BookID == bookId);
            if (selectedBook != null)
            {
                _sCart.RemoveFromCart(selectedBook);
            }
            return RedirectToAction("Index");
        }
    }
}

GameLibrary/Views/SCarts/Create.cshtml
@model GameLibrary.Models.SCart

@{
    ViewData["Title"] = "Create";
}

<h1 style="font-family:Montserrat;">Create</h1>

<h4 style="font-family:Montserrat;">ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SCartId" class="control-label"></label>
                <input asp-for="SCartId" class="form-control" />
                <span asp-validation-for="SCartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameLibrary/Views/SCarts/Delete.cshtml
@model GameLibrary.Models.SCart

@{
    ViewData["Title"] = "Delete";
}

<h1 style="font-family:Montserrat;">Delete</h1>

<h3 style ="font-family:Montserrat;">Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SCartId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GameLibrary/Views/SCarts/Details.cshtml
@model GameLibrary.Models.SCart

@{
    ViewData["Title"] = "Details";
}

<h1 style="font-family:Montserrat;">Details</h1>

<div>
    <h4 style="font-family:Montserrat;">ShoppingCart</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SCartId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GameLibrary/Views/SCarts/Edit.cshtml
@model GameLibrary.Models.SCart

@{
    ViewData["Title"] = "Edit";
}

<h1 style="font-family:Montserrat;">Edit</h1>

<h4 style="font-family:Montserrat;">ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SCartId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameLibrary/Views/SCarts/Index.cshtml
@model SCartViewModel
@using GameLibrary.ViewModels

@*<div class="row checkoutForm">
        <h2>Your shopping cart</h2>
        <table class="table table-bordered table-striped">
            <tbody>
                @foreach (var item in Model.SCart.SCartItems)
                {
                    <tr>
                        <td class="text-left">@item.Book.BookTitle</td>
                        <td class="text-left">@item.Book.BookAuthor</td>
                        <td class="text-left">
                            <a href="@Url.Action("Details", "Books", new { id = item.Book.BookID})" title="@item.Book.BookTitle" class="links">
                                <img class="img-responsive" src="@Url.Content("~/images/" + @item.Book.BookImage)" height="100" width="100" alt="">
                            </a>
                        </td>
                        <td class="text-right">@item.Book.BookPrice.ToString("c")</td>
                        <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" href="@Url.Action("RemoveFromShoppingCart", "SCarts", new { bookId = item.Book.BookID })" class="links">Remove</a>

                    </tr>
                }
            </tbody>
        </table>
    </div>*@

<div class="row checkoutForm">
    <h2 style="font-family:Montserrat;">Your reservation cart</h2>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Book</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.SCart.SCartItems)
            {
            <tr>
                <td class="text-center">@line.Amount</td>
                <td class="text-left">@line.Book.BookTitle</td>
                <td class="text-right">@line.Book.BookPrice.ToString("c")</td>
                <td class="text-right">
                    @((line.Amount * line.Book.BookPrice).ToString("c"))
                </td>
                <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="SCart" asp-action="RemoveFromShoppingCart" asp-route-drinkId="@line.Book.BookID"></a></td>
                @*<td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" href="@Url.Action("RemoveFromShoppingCart", "SCarts", new { bookId = line.Book.BookID })" class="links">Remove</a>*@
            </tr>

            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.SCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            @*<a class="btn btn-success" asp-controller="Orders" asp-action="Create">Check out</a>*@
            <a class="btn btn-success" href="@Url.Action("create", "Orders", new { SCartId = Model.SCart.SCartId })">Check out</a>
            @*<a class="btn btn-success" href="@Url.Action("ClearAll", "SCarts", new { SCartId = Model.SCart.SCartId })">Check out</a>*@
        </div>
    </div>
</div>